### ISSUE TITLE
Adding data created by the Java N5 implementation

### ISSUE THREAD

**Issue by jakirkham** [constantinpape/zarr_implementations#1]
To get a full comparison, it would be very useful to include data created by the Java N5 implementation as well.

**Comment by constantinpape** [comment]
Yes, should definitely include that.
I will try to cook something up with my limited Java skills later.

**Comment by jakirkham** [comment]
We could also reach out for help. Maybe @hanslovsky or others could advise on how best to proceed.

**Comment by hanslovsky** [comment]
I suggest you have a look at [`N5Utils.save`](https://github.com/saalfeldlab/n5-imglib2/blob/350788182aaefdf67fcfb658e2374ae0c5007028/src/main/java/org/janelia/saalfeldlab/n5/imglib2/N5Utils.java#L1180). Use the methods in the [`ArrayImgs`](https://github.com/imglib/imglib2/blob/43f4b1a0a7db6c6bb734dc53ba0288acf0455c91/src/main/java/net/imglib2/img/array/ArrayImgs.java) class to create the data.

**Comment by constantinpape** [comment]
Ok, I started to implement this and I think there is not much missing:
https://github.com/constantinpape/zarr_implementations/blob/n5-java/generate_data/n5-java/src/main/java/zarr_implementations/n5_java/App.java

AFAICT there are still two issues:
- imageio reads data as `int`, but we want to store as `uint8` in n5. How do we convert this?
- block sizes for edge sizes must be adapted (should be trivial)

@hanslovsky sry, saw your comment after I had the bulk of this done. But I personally would 
like to stay clear of imglib, which does not make life easier with limited java skills....
I made a PR https://github.com/constantinpape/zarr_implementations/pull/2
and any comments / suggestions would be welcome.

**Comment by hanslovsky** [comment]
Is the image RGB? Then it might actually be a 2D image with `ARGB` values at each pixel if you look at an int array.

Still my suggestion: using imglib2 will make this a lot easier.

**Comment by hanslovsky** [comment]
See #3 

Naming of packages etc. could probably be more java-like but that is a minor concern. It is probably best to pass the input and output files as parameters, so you are not restricted to execute the script from within a specific directory. Also, you can specify a main class, then you can execute the program just like 
```sh
java -jar target/n5_java-1.0.0.jar
```

**Comment by constantinpape** [comment]
Thanks for the PR! I merged it and I can take it from here.

> Still my suggestion: using imglib2 will make this a lot easier.

Sure, I was not opposed to imglib2 in general, just wouldn't want to delve into it if I had 
to write the code myself. Anyway that's fixed now thanks to your PR.

> Naming of packages etc. could probably be more java-like but that is a minor concern. It is probably best to pass the input and output files as parameters, so you are not restricted to execute the script from within a specific directory.

I think for now this is fine as it is. We can revisit these issues if we decide to include more example data here.

**Comment by constantinpape** [comment]
@hanslovsky 
I can build the java code now (using `mvn clean package`), but I can't run it.

I tried via `java -jar`, [see](https://github.com/constantinpape/zarr_implementations/blob/n5-java/generate_data/n5-java/generate_data.sh#L2) but ran into 
```
no main manifest attribute, in target/n5_java-1.0.0.jar
``` 
I also tried `java -cp`, [see](https://github.com/constantinpape/zarr_implementations/blob/n5-java/generate_data/n5-java/generate_data.sh#L3), but ran into
```
Error: Could not find or load main class zarr_implementations.n5_java.App
```
Any ideas?

**Comment by hanslovsky** [comment]
> I tried via `java -jar`, [see](https://github.com/constantinpape/zarr_implementations/blob/n5-java/generate_data/n5-java/generate_data.sh#L2) but ran into

You would have to define a main class in the pom for that to work.

> I also tried `java -cp`, [see](https://github.com/constantinpape/zarr_implementations/blob/n5-java/generate_data/n5-java/generate_data.sh#L3), but ran into

I forgot to add the package on top of the file, sorry. Filed another PR, then it will work.

Another suggestion: Use an image that has different dimension sizes. This would make certain errors (e.g. axis order) more obvious.

**Comment by hanslovsky** [comment]
> Sure, I was not opposed to imglib2 in general, just wouldn't want to delve into it if I had
to write the code myself. Anyway that's fixed now thanks to your PR.

These are probably good entry points:
 - https://imagej.net/ImgLib2_Examples
 - https://nbviewer.jupyter.org/github/imagej/tutorials/blob/master/notebooks/3-Advanced-Usage/2-ImgLib2-in-Detail.ipynb
 - https://forum.image.sc/ for questions

**Comment by constantinpape** [comment]
Thanks for the new PR. I can build and run now.
However, the axis order is flipped compared to the zarr / z5py data.
See 
https://github.com/constantinpape/zarr_implementations/blob/n5-java/data/zarr.n5/raw/attributes.json#L11-L14
 https://github.com/constantinpape/zarr_implementations/blob/n5-java/data/n5-java.n5/raw/attributes.json#L1

I guess this is due to [this line](https://github.com/constantinpape/zarr_implementations/blob/n5-java/generate_data/n5-java/src/main/java/zarr_implementations/n5_java/App.java#L52).

Would it be possible to change this?

**Comment by constantinpape** [comment]
> Another suggestion: Use an image that has different dimension sizes. This would make certain errors (e.g. axis order) more obvious.

Yes, that's probably a good idea. I will make an issue about what data to use once we have merged the n5-java PR.

**Comment by hanslovsky** [comment]
You can remove the `Views.moveAxis` (similar to `np.transpose`) call to leave the channel axis in the first (`0` index) dimension of the image. You would need to adjust the block size accordingly. `x` and `y` might still be flipped, that's why I suggested using an image width `height != width`.

`Views.invertAxis` inverts the index mapping for a particular axis, i.e. `1 -> -1` but does not change the order of the axes.

**Comment by constantinpape** [comment]
Thanks, removing `moveAxis` fixed the issue.
I have added the data and merged the PR.

**Comment by jakirkham** [comment]
Thanks for your help @hanslovsky :)
