### ISSUE TITLE
Publish on GitHub Pages

### ISSUE THREAD

**Issue by thewtex** [constantinpape/zarr_implementations#16]
Well done on this nice test suite!

I would like to also use this for testing JavaScript / WebAssembly implementation in itk-vtk-viewer.

Could GitHub Pages please be enabled on the `master` branch? The goal is to provide the `data` directory available via http.

Thanks!

**Comment by constantinpape** [comment]
> Well done on this nice test suite!

Thanks! I will also try to extend and update this some time in the future (but I am too busy with other projects to do much zarr / z5 work right now).

> Could GitHub Pages please be enabled on the `master` branch? The goal is to provide the `data` directory available via http.

It should be enabled now. Let me know if you need anything else for this.

**Comment by thewtex** [comment]
Verified -- perfect! Thanks @constantinpape ! :pray:

**Comment by joshmoore** [comment]
:+1:
