### ISSUE TITLE
Better name for blosc Zarr dataset

### ISSUE THREAD

**Issue by jakirkham** [constantinpape/zarr_implementations#6]
The dataset [currently called `blosc`]( https://github.com/constantinpape/zarr_implementations/tree/afd64fe06b9550c2ef7d26455fa5a2a1c35c7b78/data/zarr.zr/blosc ) is really an `lz4` dataset. Would be nice to name this a little more clearly (particularly as `blosc` supports many compressors).

**Comment by constantinpape** [comment]
Yes, that's a very good point.
I would suggest changing the structure to `blosc/lz4`. We could then also add more blosc compressed datasets in the same manner.

**Comment by jakirkham** [comment]
It's worth noting there are two paths to LZ4-style compression in Zarr.

1. Blosc (as this is using)
2. LZ4 via [`LZ4_compress_fast`]( https://github.com/lz4/lz4/blob/v1.8.3/lib/lz4.h#L171-L178 )

OTOH N5 uses lz4-java's `LZ4BlockOutputStream`, which uses a [custom blocked lz4 algorithm]( https://github.com/lz4/lz4-java/blob/16ec10dc369420e1790e3ca6156e7013753c683d/src/java/net/jpountz/lz4/LZ4BlockOutputStream.java#L27-L31 ).

As it stands, these are incompatible. Have raised issue ( https://github.com/zarr-developers/numcodecs/issues/175 ) to discuss how we want to resolve this.

**Comment by constantinpape** [comment]
@jakirkham
I changed this in #7. Please check it out  and see if that is what you had in mind.
